### ISSUE TITLE
Theather insert Configurate sheet dosen't open

### ISSUE THREAD

**Issue by Atzaelll** [League-of-Foundry-Developers/fvtt-module-theatre#162]
**Module Version:** v2.6.1

**Describe the bug**
When I tried to click on the theather insert configuration, to change the base image or the image of the emotes it doesn't open or really anything happens.

**Browser:**
 - google chrome

**Foundry Version:** 
11

**Game System:** 
5e

**Comment by megahead11** [comment]
The current version of theatre is 2.8.0
At the moment, foundry and forge are not pulling the download because of some issues with the module management.

If you are not using forge, you can actually install it using the json from this link: https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/releases/tag/v2.8.0
