### ISSUE TITLE
Theatre Inserts do not appear on right side of screen

### ISSUE THREAD

**Issue by SeattleSasquatch** [League-of-Foundry-Developers/fvtt-module-theatre#32]
### Steps
1. Start a foundry server with two actors and the Theatre Inserts installed.
2. Display both actors' theatre inserts.

### Results
- The Theatre Insert on the right side of the does not appear.
![exampleImage](https://user-images.githubusercontent.com/21186541/118383409-2d13a380-b5b2-11eb-9aca-afb5bf8e5586.png)

**Comment by SeattleSasquatch** [comment]
I believe I have found a fix in #33.

**Comment by megahead11** [comment]
Out of curiosity, do you get this issue with no other modules installed? I can't seem to reproduce this in vanilla or my own setup.

**Comment by SeattleSasquatch** [comment]
Just made a fresh foundry thing to double check and no I cannot get it to reproduce with theatre inserts by itself. Should have checked that earlier, my bad. I'll go through my other modules and see which of them is causing the issue. 

For reference, these are the modules that are activated at the same time: 
![image](https://user-images.githubusercontent.com/21186541/119220292-b63d4580-ba9e-11eb-83d3-b01ebde2894b.png)

**Comment by megahead11** [comment]
Hm. Yeah, it's not the first time perfect visions seems to cause conflicts. It is pretty vexing knowing that some of the stuff for the theatre stage is drawn through the pixi renderer since it's explained why a few of my attempts to edit the css earlier has failed. 
I believe someone who was working on an update mentioned there was a bit of an issue here, so we'll have to see what potential solutions they might have; though I'll have to test the PR you have in case that might be fine for the meantime.
Ideally I'd want to make sure  we have a long term fix; some updates for 0.8.x are on the way.
